name: publish-container
on:
  push:
    branches:
    - master

jobs:
  publish-app:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/ashwinath
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup GitHub Container Registry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build and push
      run: make
